const SET_ROLE = 'SET_ROLE'
const SET_PERMISSION_ROUTES = 'SET_PERMISSION_ROUTES'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const RESOURCES = 'RESOURCES'
// 显示图片LOGO的路径
const LOGO_IMG_PATH = 'LOG_IMG_PATH'

export {
  SET_ROLE,
  SET_PERMISSION_ROUTES,
  TOGGLE_SIDEBAR,
  RESOURCES,
  LOGO_IMG_PATH // 图片路径
}
