server:
  port: ${port:8200}
spring:
  application:
    name: xifu-gateway
  cloud:
    gateway:
      discovery:
              locator:
                enabled: true
      routes:
      - id: xifu-user
        uri: lb://xifu-user
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1 # 表示去掉两个前缀即去掉/api/user ==> http://serviceId/**
      - id: xifu-auth
        uri: lb://xifu-auth
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1 # 表示去掉两个前缀即去掉/user ==> http://serviceId/**
      - id: xifu-filemanage
        uri: lb://xifu-filemanage
        predicates:
        - Path=/fileManager/**
        filters:
        #- StripPrefix=1 # 表示去掉两个前缀即去掉/user ==> http://serviceId/**
        - name: RequestSize
          args:
            maxSize: 5000000
#      httpclient: # 连接超时时间
#        connect-timeout: 10
      # 设备服务模块的请求服务
      - id: xifu-dev-service
        uri: lb://xifu-dev-service
        predicates:
        - Path=/dev/**
        filters:
        - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: ${eurekaServiceUrl:http://127.0.0.1:7001/eureka/}
