server:
  port: ${port:7001}
#eureka的主机名
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# 打印对应的包下的日志
logging:
  level:
    xifu.com: debug
    org: info
    com: info
  path: D:/xifu/logs
  file: D:/xifu/logs/register.log