server:
  port: ${prot:8400}
spring:
  application:
    name: xifu-filemanage
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/user_database?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true

# 注册到eureka中
eureka:
  client:
    serviceUrl:
      defaultZone: ${eurekaServiceUrl:http://127.0.0.1:7001/eureka/}
xifu:
  file:
    windowPath: D:/fileManager/xifu # windows的存储路径
    linuxPath: /srv/fileManager/imageManager # linux的存储路径
    fileMaxSize: 3145728